
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTIVO ALIANZA_EQ ASIGNATURA BOOLEAN CARGO CARRERA COMA COMILLA CONCLUSION_PROY CORCHETE_D CORCHETE_I DIRECCION DOSPUNTOS EDAD EMAIL EQUIPOS ESTADO_PROY FECHA FECHA_FIN FECHA_INICIO FECHA_VALOR FIRMA_DIGITAL FLOAT FOTO HABILIDADES IDENTIDAD_EQ INTEGER LINK LLAVE_D LLAVE_I NOMBRE NOMBRE_EQ NOMBRE_PROY NULL PROYECTOS RESUMEN_PROY SALARIO STRING TAREAS_PROY UNIVERSIDAD_REG URL VERSION VIDEO_PROYjson : LLAVE_I estructura_equipo LLAVE_Destructura_equipo : EQUIPOS DOSPUNTOS CORCHETE_I lista_equipos CORCHETE_Dlista_equipos : equipo\n                     | equipo COMA lista_equiposequipo : LLAVE_I atributos_equipo LLAVE_Datributos_equipo : NOMBRE_EQ DOSPUNTOS STRING COMA ASIGNATURA DOSPUNTOS STRING'
    
_lr_action_items = {'LLAVE_I':([0,7,12,],[2,10,10,]),'$end':([1,5,],[0,-1,]),'EQUIPOS':([2,],[4,]),'LLAVE_D':([3,11,13,22,],[5,-2,16,-6,]),'DOSPUNTOS':([4,14,20,],[6,17,21,]),'CORCHETE_I':([6,],[7,]),'CORCHETE_D':([8,9,15,16,],[11,-3,-4,-5,]),'COMA':([9,16,18,],[12,-5,19,]),'NOMBRE_EQ':([10,],[14,]),'STRING':([17,21,],[18,22,]),'ASIGNATURA':([19,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'json':([0,],[1,]),'estructura_equipo':([2,],[3,]),'lista_equipos':([7,12,],[8,15,]),'equipo':([7,12,],[9,9,]),'atributos_equipo':([10,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> json","S'",1,None,None,None),
  ('json -> LLAVE_I estructura_equipo LLAVE_D','json',3,'p_json','Lexer.py',135),
  ('estructura_equipo -> EQUIPOS DOSPUNTOS CORCHETE_I lista_equipos CORCHETE_D','estructura_equipo',5,'p_estructura_equipo','Lexer.py',139),
  ('lista_equipos -> equipo','lista_equipos',1,'p_lista_equipos','Lexer.py',143),
  ('lista_equipos -> equipo COMA lista_equipos','lista_equipos',3,'p_lista_equipos','Lexer.py',144),
  ('equipo -> LLAVE_I atributos_equipo LLAVE_D','equipo',3,'p_equipo','Lexer.py',151),
  ('atributos_equipo -> NOMBRE_EQ DOSPUNTOS STRING COMA ASIGNATURA DOSPUNTOS STRING','atributos_equipo',7,'p_atributos_equipo','Lexer.py',155),
]
